name: solid_rgb
version: 0.1.0
publish_to: none
description: Solid Software test task.
environment: 
  sdk: '>=3.0.2 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  solid_lints: ^0.0.16
flutter: 
  uses-material-design: true
